### ISSUE TITLE
ble.py line 395

### ISSUE THREAD

**Issue by Encartele** [OmronMicroDevices/envsensor-observer-py#1]
Are you guys active on here? I'm throwing an error on this line:
ncmd, opcode = struct.unpack("<BH", pkt[:3])
With this error:
error: unpack requires a string argument of length 3

Do you know what could be causing this?

**Comment by Encartele** [comment]
I figured out the issue with this. I had enabled something otherwise previously disabled.
Could you guys give an example of the command to send to the sensor to change the beacon?
It seems that I should go through the bluetoothctl, connect to the sensor, then is it a an attribute command, a write command?
There are a few viewable attributes, they all have the same UUIDs minus the second 4 characters which is 3000, 3010, 3030, and 3040 I believe. So I would write to that UUID and exactly how would I phrase the command?

**Comment by Encartele** [comment]
To anyone reading this. To change the beacon to work with this program:
bluetoothctl (to enter the bluetooth commands)
scan on (to find the Omron sensor, my MACs started with D4)
connect $macaddress
select-attribute /org/bluez/hci0/dev_(mac address separated by underscores, not colons)/service0044/char0047
read (this will show you the byte data that is written in that UUID)
write 0x** 0x** (follow this format for all 9 bytes copying the data from the read results, then on the 8th byte you will overwrite the default 0x08 with 0x02)
read (to verify the 8th byte is correctly written)
disconnect
take out the sensor battery and put it back in, then run the envsensor_observer.py program

**Comment by OMRON-ME** [comment]
@Encartele 
You are right.
Setting Becon Mode to 0x02 or 0x04 (0x08 by default) in ADV setting (Characteristics UUID: 0x3042) makes the sensor beacon broadcaster which can be handled by this observer script.
Thank you very much for your support.
[communication interface manual](https://omronmicrodevices.github.io/products/2jcie-bl01/communication_if_manual.html#idx-02-04-02)
