### ISSUE TITLE
Configuration of the sensor as a beacon broadcaster (IM/EP)

### ISSUE THREAD

**Issue by eercanayar** [OmronMicroDevices/envsensor-observer-py#2]
Hi everyone,

I want to check the env sensor with raspberry pi 3 like you did. But I'm stuck at how to configure the env sensor as a beacon broadcaster (IM/EP? You noticed this on readme as;

> Environment Sensor (2JCIE-BL01) must be configured as a beacon broadcaster (IM/EP).

Is there any configuration tool or something to achieve this?

Thanks,
Emir

**Comment by OMRON-ME** [comment]
@eercanayar 

You need to change the beacon mode setting of the sensor by changing the value in ADV setting characteristic (Characteristics UUID: 0x3042).
Please refer to this comment on how to configure the beacon mode to IM or EP.
https://github.com/OmronMicroDevices/envsensor-observer-py/issues/1#issuecomment-388171581

To do this, you can use any of generic BLE central application like gattools on Linux, LightBlue on iOS or nRFconnect on Android.

[communication interface manual](https://omronmicrodevices.github.io/products/2jcie-bl01/communication_if_manual.html#idx-02-04-02)
