### ISSUE TITLE
0c4c3001

### ISSUE THREAD

**Issue by Encartele** [OmronMicroDevices/envsensor-observer-py#3]
Hey guys,
So I'm rewriting this for nodejs and instead of getting the advertising events, I'm literally just reading the last values bytes.
Below is the print out of what my code is giving.

Found UUID. #This is the 0c4c3000 UUID
Found child UUID. #This is the 0c4c3001 UUID
30fb0776103a0002000126a90d86197206650b #This is the entire byte string that I am getting back from all 19 bytes)
Skipping byte. #This is the first byte, which as far as I could tell from your communications manual isn't used for anything on the reading side, right?
Hex: fb7 #This is byte 1 and 2 (for temp) converted to signed (removed the 0)
Int: 4023 #This is the value converted from Hex to Decimal. This converted to Fahrenheit is 104.4 degrees in an air conditioned lab.
Hex: 7610 #For humidity
Int: 30224 #I'm guessing that whatever the number is, only use the first 4? 30.22% humidity does sound right.
Hex: 3a0
Int: 928 #This is for lx. In the communication manual it says it's .01 in its readings. In a number like this, it seems more likely that it is 92.8 lx, is this a situation where code shouldn't have removed one of the two zeroes?
Hex: 20
Int: 32 # It's indoors, .32 UV sounds fine.
Hex: 126
Int: 294 # It should be around 8000 hPa to be around 25 in mercury.
Hex: a9d
Int: 2717 # 27.17 dB is probably right
Hex: 8619
Int: 34329 # Again omit the 5 character? 34.32 discomfort index?
Hex: 726
Int: 1830 # 18.3 * C in heatstroke. 
Hex: 650b # Kept the leading edge 0 as it's unsigned
Int: 25867 # 2.586 Volts sounds right.

So, I get some strange readings with some seemingly accurate readings, but the one that bothers me the most is the temperature. Am I doing the conversions correctly? Take the bytes and convert directly to decimal using 16 bit?

**Comment by OMRON-ME** [comment]
@Encartele  

You need to parse all 16bit values in little-endian format.
The first byte 0x30 is the sequencial number indicating the data is updated or not.
Each 16bit (little-endian) values from 2nd byte of the entire byte string shows the measurement result from each sensors.

- HEX : 0x07FB => DEC : 2043 => Temperature : 20.43 degC
- HEX : 0x1076 => DEC : 4214 => Humidity : 42.14 %RH
- HEX : 0x003A => DEC : 58 => Light : 58 lx
- HEX : 0x0002 => DEC : 2 => UVI : 0.02
- HEX : 0x2601 => DEC : 9729 => Pressure : 972.9 hPa
- HEX : 0x0DA9 => DEC : 3497 => Sound noise : 34.97 dB
- HEX : 0x1986 => DEC : 6534 => Discomfort Index : 65.34
- HEX : 0x0672 => DEC : 1650 => Heat Stroke Risk : 16.50
- HEX : 0x0B65 => DEC : 2917 => Battery Voltage : 2917 mV = 2.917 V

**Comment by Encartele** [comment]
Hey, I got it. Thanks. With the way Javascript did all the conversions and everything I just had to remove a loop and manually parsed the byte string then formatted and did the math that way.
