### ISSUE TITLE
Where does the  "Discomfort Index" and "Heat Stroke Risk" calculation come from?

### ISSUE THREAD

**Issue by bunnyevans** [OmronMicroDevices/envsensor-observer-py#4]
Temperature (degC),Humidity (%%RH),
Discomfort Index,Heat Stroke Risk,
27.16,43.39,
73.76,22.2,

While dimensionless, I can find no details of what turns 27'C 43%RH 
into DI 73.76 or HSR 22.2

There does not appear to be any documentation on this.
What reference was used to generate these values?

**Comment by OMRON-ME** [comment]
@bunnyevans 
Refer to Communication Interface Manual :
(*2) Discomfort Index, Heatstroke risk factor (WBGT approximation) are calculated only by temperature and humidity. These information is just a rough indication and for referential use only.

**Comment by bunnyevans** [comment]
Thank you, I found that section after you mentioned the magic word WBGT
However, there is no explanation of the discomfort index.

Currently:
T = 31.25
H = 63%

HSR = 27.8 (which seems in line with WBGT)
DI = 80.9

The Discomfort index is a mystery. in the sensor_beacon.py we find:
return (0.81 * temp) + 0.01 * humi * ((0.99 * temp) - 14.3) + 46.3

https://keisan.casio.com/exec/system/1351058230 Seems to think that DI = WBGT and gives 27.8
DI = T - 0.55(1-0.01H).(T-14.5)

Perhaps I need to ask Omron nicely?

**Comment by OMRON-ME** [comment]
@bunnyevans 
This is just a matter of unit conversion between degC and degF.
The formula in sensor_beacon.py generate DI value in Fahrenheit expression while the argument is in Celsius.
So, the conversion of C and F is also implemented in this DI calculation formula.
